### ISSUE TITLE
Export parameters to ENV instead of parsing template

### ISSUE THREAD

**Issue by Halama** [keboola/aws-parameter-filler#1]
- Stáhne všechny parametry pod určitým prefixem např. `/keboola/kbc-us-east-1/oauth-api/*` a podle jejich jmen je exportne jako `ENV` proměnné
- bude se pouštět jako první krok v entrypoint při nahození kontejneru s appku podobně jako tady https://www.whaletech.co/2017/08/01/Secure-Credentials-for-ECS-Tasks.html 
- v parametrech appky pak budou referencované `ENV` proměnné jako tady https://github.com/keboola/auth-api/pull/1/files#diff-b92c32c53e9112e965dac7dd4a0ebcc1R18

**Comment by Halama** [comment]
Tahle věc je koukám vlastně to samé https://github.com/Droplr/aws-env#usage :)

**Comment by odinuv** [comment]
fixed in a5e7bd7cefa554e4482c9f291e263fd4fd2841e1
