### ISSUE TITLE
Lower PHP requiremenets

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/aws-parameter-filler#3]
Current connection repo is at 7.1.3. Therefore this package cannot be used:
```
Package keboola/aws-parameter-filler at version  has a PHP requirement incompatible with your PHP version (7.1.23)
```
Is there a reason for 7.2 or could we lower to 7.1? 

Related: https://github.com/keboola/connection/issues/1590

**Comment by tomasfejfar** [comment]
Oh, doh, it also conflicts with symfony/config :/

**Comment by tomasfejfar** [comment]
Seems like I'll need to reimplement it. It's a dependency hell.

**Comment by odinuv** [comment]
Afaik to celý pojede s libovolnou verzi php í symfony, dej si tam roury

**Comment by tomasfejfar** [comment]
Tak je to v prčicích - potřebuje to php-component a ta má SF v4 od verze 1. A na symfony/config to tím pádem bude konfliktit vždycky :/ 

Takže veskrze je to:
* na update v connection 
* nebo zabalit a udělat z toho shim
* reimplementovat v connection

**Comment by tomasfejfar** [comment]
Ještě zkusím update connection na sf4

**Comment by tomasfejfar** [comment]
Tak taky neúspěšně `keboola/debug-log-uploader v2.0.0 requires symfony/filesystem ~2.3|~3.0`. Kdo ví, co dalšího to ještě zablokuje. Mám to zkoušet?

**Comment by tomasfejfar** [comment]
Ha, tak to vypadá, že by ten log uploader mohl být poslední v řadě! :D

**Comment by ujovlado** [comment]
Ale ten debug-log-uploader asi mozeme poladit aby fical aj na 4ke

**Comment by tomasfejfar** [comment]
jj to jsem právě zkusil - imho v sf/fs není žádný zásadní bc break (minimálně v tom jak se tam používá). Teď to izoluju celé do PR na connection a jednotlivé PR sem a do toho log uploaderu...

**Comment by odinuv** [comment]
je tam zasadni bc break az u 4.2 tusim, kde Process prestal v ctoru podporovat string argument

**Comment by Halama** [comment]
jakoze bc break v minor verzi?

**Comment by odinuv** [comment]
myslim, ze to ve 4 deprekovali a ve 4.2 odstranili ale mozna kecam

**Comment by tomasfejfar** [comment]
Jo, to jsme vlastně řešili s mirem, myslím. Jako breaků tam bylo víc (musel jsem nakonec updatnout stejně connection). Resp. je jich tam spoustu mezi 2.7 a 4.2 :( Ale myslím, že skoro všechno je řešitelný. Teď jsem vyřešil pár věcí v DI a ještě něco zbývá...
