### ISSUE TITLE
Parameters are not decrypted

### ISSUE THREAD

**Issue by Halama** [keboola/aws-parameter-filler#5]
Execution:
```
 php /var/www/html/vendor/bin/aws-parameter-filler /var/www/html/.env.downloaded /keboola/$KEBOOLA_STACK/connection/ $AWS_REGION
```

Downloaded parameters:

![image](https://user-images.githubusercontent.com/903531/53340027-3bf5d900-3908-11e9-8d09-9e082c539999.png)

Version: `0.2.2`

**Comment by ujovlado** [comment]
~v tej premennej AWS_REGION ale vidim nejaky blud :)~ aha sorry, zasifrovane 🤦‍♂️

**Comment by Halama** [comment]
Mělo by stačit přidat [WithDescription](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html#systemsmanager-GetParametersByPath-request-WithDecryption)

https://github.com/keboola/aws-parameter-filler/blob/4fe476a5ce27511b530593007f0e53c388c75132/src/Component.php#L83
